name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: hackportal
          envVariableKeys: MONGODB_URI,MONGODB_DB,NEXTAUTH_SECRET,NEXTAUTH_URL,EMAIL_HOST,EMAIL_PORT,EMAIL_USER,EMAIL_PASS,EMAIL_FROM,EMAIL_SECURE
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TARGET_MONGODB_URI: preview,development,production
          TYPE_MONGODB_URI: encrypted

          MONGODB_DB: ${{ secrets.MONGODB_DB }}
          TARGET_MONGODB_DB: preview,development,production
          TYPE_MONGODB_DB: encrypted

          SPREADSHEET_ID: ${{ secrets.NEXTAUTH_SECRET }}
          TARGET_NEXTAUTH_SECRET: preview,development,production
          TYPE_NEXTAUTH_SECRET: encrypted

          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          TARGET_NEXTAUTH_URL: preview,development,production
          TYPE_NEXTAUTH_URL: encrypted

          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          TARGET_EMAIL_HOST: preview,development,production
          TYPE_EMAIL_HOST: encrypted

          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          TARGET_EMAIL_PORT: preview,development,production
          TYPE_EMAIL_PORT: encrypted

          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          TARGET_EMAIL_USER: preview,development,production
          TYPE_EMAIL_USER: encrypted

          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TARGET_EMAIL_PASS: preview,development,production
          TYPE_EMAIL_PASS: encrypted

          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          TARGET_EMAIL_FROM: preview,development,production
          TYPE_EMAIL_FROM: encrypted

          EMAIL_SECURE: ${{ secrets.EMAIL_SECURE }}
          TARGET_EMAIL_SECURE: preview,development,production
          TYPE_EMAIL_SECURE: encrypted


      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
